// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIX_w_Community
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSIX_w_Community.8bdc77e9-3751-48d3-8a94-e218d5573e92";
        public const string Name = "VSIX_w_Community";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
